[package]
name = "mithril-doc"
version = "0.1.14"
description = "An internal crate to generate documentation."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
include = ["**/*.rs", "Cargo.toml", "README.md", ".gitignore"]

[dependencies]
clap = { version = "4.5.23", features = ["derive", "env"] }
config = "0.14.1"
mithril-doc-derive = { path = "../mithril-doc-derive" }

[dev-dependencies]
regex = "1.11.1"

[features]
default = []
