[package]
name = "mithril-end-to-end"
version = "0.4.75"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
default-run = "mithril-end-to-end"

[[bin]]
name = "load-aggregator"
test = false
bench = false

[dependencies]
anyhow = "1.0.97"
async-recursion = "1.1.1"
clap = { version = "4.5.32", features = ["derive"] }
indicatif = { version = "0.17.11", features = ["tokio"] }
mithril-common = { path = "../../mithril-common", features = ["full"] }
mithril-doc = { path = "../../internal/mithril-doc" }
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_trace",
] }
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }

[features]
default = []
allow_skip_signer_certification = []
bundle_tls = ["reqwest/native-tls-vendored"]
