services:
  mithril-signer:
    image: ghcr.io/input-output-hk/mithril-signer:${MITHRIL_IMAGE_ID}
    container_name: mithril-signer-${SIGNER_ID}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=${AGGREGATOR_ENDPOINT}
      - NETWORK=${NETWORK}
      - RUN_INTERVAL=120000
      - DB_DIRECTORY=/mithril-aggregator/cardano/db
      - DATA_STORES_DIRECTORY=/mithril-signer-${SIGNER_ID}/mithril/stores
      - STORE_RETENTION_LIMIT=5
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
      - ERA_READER_ADAPTER_TYPE=${ERA_READER_ADAPTER_TYPE}
      - ERA_READER_ADAPTER_PARAMS=${ERA_READER_ADAPTER_PARAMS}
      - ENABLE_METRICS_SERVER=${ENABLE_METRICS_SERVER}
      - METRICS_SERVER_IP=${METRICS_SERVER_IP}
      - METRICS_SERVER_PORT=${METRICS_SERVER_PORT}
    volumes:
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/mithril:/mithril-signer-${SIGNER_ID}/mithril
    command: ["-vvv"]
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  default:
    external: true
    name: mithril_network
