[package]
name = "mithril-client-wasm"
version = "0.8.6"
description = "Mithril client WASM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
categories = ["cryptography"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
chrono = { version = "0.4.40", features = ["serde"] }
mithril-client = { path = "../mithril-client", default-features = false, features = ["unstable"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["BroadcastChannel", "console", "Storage", "Window"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[build-dependencies]
mithril-build-script = { path = "../internal/mithril-build-script" }

[features]
# Include nothing by default
default = []
test-node = []

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
# wasm-bindgen-futures is required to build the project, but it's not used in the code
ignored = ["wasm-bindgen-futures"]
