[package]
name = "mithril-client-wasm"
version = "0.7.1"
description = "Mithril client WASM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
categories = ["cryptography"]

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.83"
futures = "0.3.31"
mithril-client = { path = "../mithril-client", features = ["unstable"] }
serde = { version = "1.0.215", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.97"
wasm-bindgen-futures = "0.4.47"
web-sys = { version = "0.3.74", features = ["BroadcastChannel"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.47"

[build-dependencies]
mithril-build-script = { path = "../internal/mithril-build-script" }

[features]
# Include nothing by default
default = []

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
