[package]
name = "mithril-relay"
version = "0.1.37"
description = "A Mithril relay"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive", "env"] }
config = "0.15.11"
libp2p = { version = "0.55.0", features = [
    "tokio",
    "gossipsub",
    "dns",
    "identify",
    "kad",
    "macros",
    "noise",
    "ping",
    "pnet",
    "quic",
    "tcp",
    "tls",
    "websocket-websys",
    "websocket",
    "yamux",
] }
mithril-common = { path = "../mithril-common", features = ["full"] }
mithril-doc = { path = "../internal/mithril-doc" }
reqwest = { version = "0.12.15", features = [
    "json",
    "gzip",
    "zstd",
    "deflate",
    "brotli"
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_trace",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
warp = "0.3.7"

[dev-dependencies]
httpmock = "0.7.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"

[features]
bundle_tls = ["reqwest/native-tls-vendored"]
