[package]
name = "mithril-persistence"
version = "0.2.42"
description = "Common types, interfaces, and utilities to persist data for Mithril nodes."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.83"
chrono = { version = "0.4.39", features = ["serde"] }
hex = "0.4.3"
mithril-common = { path = "../../mithril-common", features = ["fs"] }
semver = "1.0.24"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
sha2 = "0.10.8"
slog = "2.7.0"
sqlite = { version = "0.36.1", features = ["bundled"] }
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["sync"] }

[dev-dependencies]
mithril-common = { path = "../../mithril-common", features = ["test_tools"] }
mockall = "0.13.1"
tokio = { version = "1.42.0", features = ["macros", "time"] }
