[package]
name = "mithril-resource-pool"
version = "0.0.2"
description = "Provide a resource pool for Mithril."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.97"
mithril-common = { path = "../../mithril-common", features = ["fs"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["sync"] }

[dev-dependencies]
mithril-common = { path = "../../mithril-common", features = ["test_tools"] }
mockall = "0.13.1"
tokio = { version = "1.44.1", features = ["macros", "time"] }
