[package]
name = "mithril-aggregator-fake"
version = "0.4.5"
description = "Mithril Fake Aggregator for client testing"
authors = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.97"
axum = { version = "0.8.1", features = ["tokio", "http1"] }
clap = { version = "4.5.32", features = ["derive"] }
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["trace", "cors"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
mithril-common = { "path" = "../../mithril-common", features = [
    "test_tools",
] }
reqwest = "0.12.15"
warp = "0.3.7"

[build-dependencies]
mithril-build-script = { path = "../../internal/mithril-build-script" }
