[package]
name = "mithril-client-cli"
version = "0.10.8"
description = "A Mithril Client"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "mithril-client"
path = "src/main.rs"

[package.metadata.deb]
depends = "$auto"
section = "utility"
extended-description = """Shows, downloads and verifies certified blockchain artifacts.

Run `mithril-client --help` to display the available options."""
assets = [["../target/release/mithril-client", "usr/bin/", "755"]]

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.83"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.23", features = ["derive", "env"] }
cli-table = "0.4.9"
config = "0.15.4"
fs2 = "0.4.3"
futures = "0.3.31"
human_bytes = { version = "0.4.3", features = ["fast"] }
indicatif = { version = "0.17.9", features = ["tokio"] }
mithril-client = { path = "../mithril-client", features = ["fs", "unstable"] }
mithril-doc = { path = "../internal/mithril-doc" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
slog-term = "2.9.1"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }

[dev-dependencies]
mithril-common = { path = "../mithril-common", features = ["test_tools"] }

[features]
bundle_tls = ["mithril-client/native-tls-vendored"]
