[package]
name = "mithril-aggregator"
version = "0.7.12"
description = "A Mithril Aggregator server"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "cardano_transactions_import"
harness = false

[[bench]]
name = "cardano_transactions_get"
harness = false

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.86"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.28", features = ["derive", "env", "cargo"] }
cloud-storage = "0.11.1"
config = "0.15.7"
flate2 = "1.0.35"
hex = "0.4.3"
mithril-common = { path = "../mithril-common", features = ["full"] }
mithril-doc = { path = "../internal/mithril-doc" }
mithril-metric = { path = "../internal/mithril-metric" }
mithril-persistence = { path = "../internal/mithril-persistence" }
mithril-resource-pool = { path = "../internal/mithril-resource-pool" }
mithril-signed-entity-lock = { path = "../internal/signed-entity/mithril-signed-entity-lock" }
mithril-signed-entity-preloader = { path = "../internal/signed-entity/mithril-signed-entity-preloader" }
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = [
    "json",
    "gzip",
    "zstd",
    "deflate",
    "brotli"
] }
semver = "1.0.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
sqlite = { version = "0.36.1", features = ["bundled"] }
tar = "0.4.43"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = { version = "0.7.13", features = ["codec"] }
uuid = { version = "1.13.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
warp = "0.3.7"
zstd = { version = "0.13.2", features = ["zstdmt"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
http = "1.2.0"
httpmock = "0.7.0"
mithril-common = { path = "../mithril-common", features = [
    "allow_skip_signer_certification",
    "test_tools",
] }
mockall = "0.13.1"
slog-scope = "4.4.0"
slog-term = "2.9.1"
tempfile = "3.16.0"

[features]
default = ["jemallocator"]

bundle_tls = ["reqwest/native-tls-vendored"]
jemallocator = ["dep:tikv-jemallocator"]
