[package]
name = "mithril-aggregator"
version = "0.5.117"
description = "A Mithril Aggregator server"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "cardano_transactions_import"
harness = false

[[bench]]
name = "cardano_transactions_get"
harness = false

[dependencies]
anyhow = "1.0.92"
async-trait = "0.1.83"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.20", features = ["derive", "env", "cargo"] }
cloud-storage = "0.11.1"
config = "0.14.1"
flate2 = "1.0.34"
hex = "0.4.3"
mithril-common = { path = "../mithril-common", features = ["full"] }
mithril-doc = { path = "../internal/mithril-doc" }
mithril-metric = { path = "../internal/mithril-metric" }
mithril-persistence = { path = "../internal/mithril-persistence" }
openssl = { version = "0.10.68", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
paste = "1.0.15"
prometheus = "0.13.4"
rayon = "1.10.0"
reqwest = { version = "0.12.9", features = ["json"] }
semver = "1.0.23"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
sqlite = { version = "0.36.1", features = ["bundled"] }
tar = "0.4.43"
thiserror = "1.0.67"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["codec"] }
typetag = "0.2.18"
uuid = { version = "1.11.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
warp = "0.3.7"
zstd = { version = "0.13.2", features = ["zstdmt"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
httpmock = "0.7.0"
mithril-common = { path = "../mithril-common", features = [
    "allow_skip_signer_certification",
    "test_tools",
] }
mockall = "0.13.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"
tempfile = "3.13.0"

[features]
default = ["jemallocator"]

bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
jemallocator = ["dep:tikv-jemallocator"]
