name: Aggregator stress test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: SHA of the commit on which the aggregator binary should be obtained.
        required: true
        type: string
      num_signers:
        description: Number of concurrent signers
        required: true
        type: string
        default: "100"
      num_clients:
        description: Number of concurrent clients
        required: true
        type: string
        default: "100"
      enable_debug:
        description: Enable debug output ("-vvv") for the aggregator stress test
        required: true
        type: boolean
        default: false

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      branch: ${{ steps.set-env.outputs.branch }}
      commit_sha: ${{ steps.set-env.outputs.commit_sha }}
      num_signers: ${{ steps.set-env.outputs.num_signers }}
      num_clients: ${{ steps.set-env.outputs.num_clients }}
      enable_debug: ${{ steps.set-env.outputs.enable_debug }}
    steps:
      - name: Prepare env variables
        id: set-env
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "branch=main" >> $GITHUB_OUTPUT
            echo "num_signers=100" >> $GITHUB_OUTPUT
            echo "num_clients=100" >> $GITHUB_OUTPUT
            echo "enable_debug=false" >> $GITHUB_OUTPUT
          else
            echo "commit_sha=${{ inputs.commit_sha }}" >> $GITHUB_OUTPUT
            echo "num_signers=${{ inputs.num_signers }}" >> $GITHUB_OUTPUT
            echo "num_clients=${{ inputs.num_clients }}" >> $GITHUB_OUTPUT
            echo "enable_debug=${{ inputs.enable_debug }}"s >> $GITHUB_OUTPUT
          fi
  stress-test:
    runs-on: ubuntu-22.04
    needs: [prepare]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Prepare environment variables
        id: prepare
        shell: bash
        run: |
          if [[ "${{ needs.prepare.outputs.enable_debug }}" == "true" ]]; then
            echo "debug_level=-vvv" >> $GITHUB_OUTPUT
          fi

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Download built artifacts (Linux-x64)
        uses: dawidd6/action-download-artifact@v6
        with:
          name: mithril-distribution-Linux-X64
          path: ./bin
          commit: ${{ needs.prepare.outputs.commit_sha }}
          branch: ${{ needs.prepare.outputs.branch }}
          workflow: ci.yml
          workflow_conclusion: success

      - name: Download test runners
        uses: dawidd6/action-download-artifact@v6
        with:
          name: mithril-tooling-Linux-X64
          path: ./bin
          commit: ${{ needs.prepare.outputs.commit_sha }}
          branch: ${{ needs.prepare.outputs.branch }}
          workflow: ci.yml
          workflow_conclusion: success

      - name: Set permissions
        shell: bash
        working-directory: ./bin
        run: |
          chmod +x ./mithril-aggregator
          chmod +x ./load-aggregator

      - name: Run the aggregator stress test
        run: |
          ./bin/load-aggregator ${{ steps.prepare.outputs.debug_level }} \
          --cardano-cli-path ./mithril-test-lab/mithril-end-to-end/script/mock-cardano-cli \
          --aggregator-dir ./bin \
          --num-signers=${{ needs.prepare.outputs.num_signers }} \
          --num-clients=${{ needs.prepare.outputs.num_clients }}
